In [68]:
print("hello")

hello

In [69]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso,LogisticRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
import warnings
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [70]:
df = pd.read_csv(r'C:\Users\AnayJoshi28\Desktop\Projects\Data Scientist Projects\ML_OPS\NEW_project_1\notebook\data\raw.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    int64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(2), int64(11)
memory usage: 30.5 KB

In [71]:
x = df.drop(columns='DEATH_EVENT')
y = df['DEATH_EVENT']

In [72]:
x

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time
0,75,0,582,0,20,1,265000.00,1.9,130,1,0,4
1,55,0,7861,0,38,0,263358.03,1.1,136,1,0,6
2,65,0,146,0,20,0,162000.00,1.3,129,1,1,7
3,50,1,111,0,20,0,210000.00,1.9,137,1,0,7
4,65,1,160,1,20,0,327000.00,2.7,116,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...
294,62,0,61,1,38,1,155000.00,1.1,143,1,1,270
295,55,0,1820,0,38,0,270000.00,1.2,139,0,0,271
296,45,0,2060,1,60,0,742000.00,0.8,138,0,0,278
297,45,0,2413,0,38,0,140000.00,1.4,140,1,1,280
298,50,0,196,0,45,0,395000.00,1.6,136,1,1,285

In [73]:
y

0      1
1      1
2      1
3      1
4      1
      ..
294    0
295    0
296    0
297    0
298    0
Name: DEATH_EVENT, Length: 299, dtype: int64

In [74]:
x_train, x_test ,y_train, y_test = train_test_split(x,y,train_size=0.2,random_state=42)

In [75]:
#Logistic regression
LR_model = LogisticRegression()
LR_model.fit(x_train, y_train)

y_pred = LR_model.predict(x_test)

print("R2_score = ",r2_score(y_test,y_pred))
print("Mean_Square_Error = ",mean_squared_error(y_test,y_pred))
print("mean_absolute_error = ",mean_absolute_error(y_test,y_pred))
print("Accuracy = ", accuracy_score(y_test,y_pred))

R2_score =  0.18861545719003048
Mean_Square_Error =  0.17916666666666667
mean_absolute_error =  0.17916666666666667
Accuracy =  0.8208333333333333

c:\Users\AnayJoshi28\Desktop\Projects\Data Scientist Projects\ML_OPS\NEW_project_1\venv\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [76]:
#Decision Tree
DT_model = DecisionTreeClassifier(max_depth= 13, min_impurity_decrease= 0.001)
DT_model.fit(x_train, y_train)

y_pred = DT_model.predict(x_test)

print("R2_score = ",r2_score(y_test,y_pred))
print("Mean_Square_Error = ",mean_squared_error(y_test,y_pred))
print("mean_absolute_error = ",mean_absolute_error(y_test,y_pred))
print("Accuracy = ", accuracy_score(y_test,y_pred))

R2_score =  -7.862253321810897e-05
Mean_Square_Error =  0.22083333333333333
mean_absolute_error =  0.22083333333333333
Accuracy =  0.7791666666666667

In [77]:
#Random Forest Regression
RFR_model = RandomForestClassifier(n_estimators=500, min_impurity_decrease=0.001)
RFR_model.fit(x_train, y_train)

y_pred = RFR_model.predict(x_test)

print("R2_score = ",r2_score(y_test,y_pred))
print("Mean_Square_Error = ",mean_squared_error(y_test,y_pred))
print("mean_absolute_error = ",mean_absolute_error(y_test,y_pred))
print("Accuracy = ", accuracy_score(y_test,y_pred))

R2_score =  0.20748486516235543
Mean_Square_Error =  0.175
mean_absolute_error =  0.175
Accuracy =  0.825

In [ ]:
ada = AdaBoostClassifier(estimator=RandomForestClassifier(n_estimators=300, min_impurity_decrease=0.001), n_estimators=30)
ada.fit(x_train, y_train)

y_pred = ada.predict(x_test)

print("R2_score = ",r2_score(y_test,y_pred))
print("Mean_Square_Error = ",mean_squared_error(y_test,y_pred))
print("mean_absolute_error = ",mean_absolute_error(y_test,y_pred))
print("Accuracy = ", accuracy_score(y_test,y_pred))

R2_score =  0.22635427313468026
Mean_Square_Error =  0.17083333333333334
mean_absolute_error =  0.17083333333333334
Accuracy =  0.8291666666666667
Custom Regression Accuracy: 18.33%

In [84]:
lasso = Lasso()
lasso.fit(x_train, y_train)

y_pred = lasso.predict(x_test)

print("R2_score = ",r2_score(y_test,y_pred))
print("Mean_Square_Error = ",mean_squared_error(y_test,y_pred))
print("mean_absolute_error = ",mean_absolute_error(y_test,y_pred))
y_pred

R2_score =  0.22196125915029574
Mean_Square_Error =  0.171803380987281
mean_absolute_error =  0.33644297806214213

array([-1.80623862e-01,  4.02022424e-02,  3.85685315e-01,  6.48241614e-01,
        3.81865494e-01, -3.44137010e-02,  3.45145761e-01,  7.56109486e-01,
        5.29519747e-01,  1.63783866e-01,  3.63648509e-01,  1.08626606e-01,
        1.22304085e-01,  2.69363186e-01,  4.37797387e-01,  7.87595518e-01,
        3.37205597e-01,  4.19136791e-01,  5.30086919e-01,  3.33213131e-01,
        2.38675063e-01,  3.78668664e-01,  2.57956932e-02,  5.42888573e-01,
        4.70618102e-01,  7.67893299e-02,  2.70182597e-02,  3.52133119e-01,
        7.85711746e-02,  3.92455379e-02,  5.07813847e-01,  4.63277561e-02,
        5.43527712e-01,  5.48593528e-01,  5.48170815e-01,  6.98510846e-01,
        4.16886223e-01,  5.05139779e-02,  3.32914633e-01,  3.95426002e-01,
        3.60775863e-01,  3.46145684e-01,  3.07932177e-01,  4.34219999e-01,
        3.00736215e-01,  1.07898552e-01,  1.89947056e-01, -4.53331031e-02,
        1.67798911e-01,  2.12825388e-01,  3.82075653e-01,  8.90713726e-02,
        4.20596882e-01,  7.90307463e-02, -1.87303806e-01,  3.33390358e-01,
        5.57651363e-02,  4.57911473e-01,  1.39680548e-01,  4.41265807e-01,
        4.80628862e-01,  1.44741183e-01,  2.30263390e-01,  2.71757286e-01,
        5.38209289e-01,  5.60482935e-01,  4.53438635e-02,  4.23608635e-01,
       -8.77079929e-03, -7.41189805e-03,  3.39101215e-01,  3.49639231e-02,
       -1.62638470e-03,  8.02785685e-02,  2.87087424e-01,  8.04790504e-02,
        4.15741841e-01,  3.94647929e-01,  2.54182964e-01,  1.35488434e-01,
        1.76638506e-01,  4.53168734e-01,  2.31874238e-01,  4.47454814e-01,
        3.72923093e-01,  3.35366040e-01,  5.95273872e-01,  4.24832955e-01,
        6.33580374e-01,  2.84148232e-01,  2.34657319e-01,  4.09330952e-01,
        1.35933114e-01,  5.78046174e-01,  5.55761261e-01,  3.61677226e-01,
        3.23537322e-04, -5.23843642e-02,  4.29890153e-01,  3.82445704e-01,
        5.71727328e-01,  5.79530808e-01,  1.57197852e-01,  2.89676009e-01,
       -1.36788178e-03,  4.20729166e-01,  5.35845831e-01,  2.45928742e-01,
        3.84261320e-01,  2.30656876e-01, -1.56625729e-01,  3.24775193e-01,
        1.36823910e-01,  2.82500439e-01, -5.84705654e-04,  3.28538235e-01,
        3.27570525e-01,  2.33179295e-01,  1.13521786e-01,  6.01259417e-01,
        4.42108758e-02,  2.02982996e-01,  2.46528799e-01,  3.57625947e-01,
        2.84776110e-02,  6.31151300e-01,  3.31203069e-01,  6.05106195e-02,
        1.12205877e-01,  7.05199178e-02,  3.59646955e-01, -8.36256037e-02,
        5.07833466e-01, -9.08786018e-02, -9.50283711e-02,  2.69969025e-02,
        1.51927411e-01,  5.07942784e-01,  3.00167733e-01,  1.22007803e-01,
        2.60586691e-01,  3.31999999e-01,  1.95822879e-01,  1.94367518e-02,
        3.48954459e-01,  4.20531199e-01,  4.80968088e-01,  3.26995121e-01,
        1.89418623e-02,  4.00965856e-01,  1.43529732e-01,  4.98839108e-02,
        2.13966822e-01, -1.82436742e-01, -7.64472502e-02,  3.28880388e-01,
        1.28031848e-01,  4.79382485e-01,  3.31970850e-02,  3.43160952e-01,
        5.09937083e-01,  5.07125515e-01,  4.49648800e-01,  3.65046555e-01,
        6.48189730e-02,  7.57007397e-02,  2.49230591e-01,  5.81206237e-01,
        3.47737207e-01,  8.12280658e-02,  1.17428139e-01,  4.36334179e-01,
        3.32449079e-01,  6.23044369e-02,  2.51850747e-01,  4.85009078e-01,
        2.83346030e-03,  3.70814809e-01,  1.35741481e-01,  5.99000473e-01,
       -1.26818727e-01, -5.30432130e-02,  3.95480440e-01, -2.70274497e-02,
        1.46674651e-02,  3.89480284e-01,  4.08583928e-01,  4.87360521e-01,
        4.12007870e-01,  2.78738840e-01,  9.31621749e-02,  4.18961177e-02,
        2.17886351e-01,  5.63113712e-01, -4.71027521e-02,  4.45706510e-03,
        5.38149047e-01,  3.50444503e-02,  6.14551526e-01,  3.21206562e-01,
        5.60504769e-01,  7.97296743e-02,  4.10638687e-01,  8.56664134e-03,
        4.83112312e-02,  2.89383679e-01,  4.29658137e-01,  3.30524509e-01,
        3.28908753e-01,  1.84912982e-02,  5.67322954e-01,  4.89329757e-01,
       -5.84551792e-02,  4.44751138e-01,  4.77148515e-01,  1.14050850e-01,
        2.87245751e-01,  5.27825050e-01,  2.71837905e-01, -1.13902921e-01,
        1.83740518e-01,  3.44041107e-01,  6.01791543e-01, -5.45810920e-02,
        3.86743273e-01,  4.11002361e-01,  5.87968160e-02,  2.40600980e-01,
        5.61406383e-01,  6.38182456e-02, -8.49669326e-02, -4.90656771e-02,
        1.47664427e-01,  6.67224992e-01,  6.28088193e-01,  4.19281610e-01,
       -5.62822429e-02,  7.10704576e-02, -7.26326955e-02,  1.90625597e-01])

In [ ]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [ ]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Classifier": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
    "AdaBoost Classifier": AdaBoostClassifier(estimator=RandomForestClassifier(n_estimators=300, min_impurity_decrease=0.001), n_estimators=30)
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train) # 

    # Make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 0.3199
- Mean Absolute Error: 0.2467
- R2 Score: 0.5012
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4404
- Mean Absolute Error: 0.3486
- R2 Score: 0.1215
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 0.3924
- Mean Absolute Error: 0.3280
- R2 Score: 0.2494
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4145
- Mean Absolute Error: 0.3364
- R2 Score: 0.2220
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 0.3199
- Mean Absolute Error: 0.2472
- R2 Score: 0.5010
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4381
- Mean Absolute Error: 0.3467
- R2 Score: 0.1308
===================================


K-Neighbors Classifier
Model performance for Training set
- Root Mean Squared Error: 0.4871
- Mean Absolute Error: 0.2373
- R2 Score: -0.1569
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.6021
- Mean Absolute Error: 0.3625
- R2 Score: -0.6416
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.0000
- Mean Absolute Error: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4958
- Mean Absolute Error: 0.2458
- R2 Score: -0.1133
===================================


Random Forest Classifier
Model performance for Training set
- Root Mean Squared Error: 0.0000
- Mean Absolute Error: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4133
- Mean Absolute Error: 0.1708
- R2 Score: 0.2264
===================================


AdaBoost Classifier
Model performance for Training set
- Root Mean Squared Error: 0.0000
- Mean Absolute Error: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4031
- Mean Absolute Error: 0.1625
- R2 Score: 0.2641
===================================

In [ ]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                 Model Name  R2_Score
6       AdaBoost Classifier  0.264093
5  Random Forest Classifier  0.226354
1                     Lasso  0.221961
2                     Ridge  0.130790
0         Linear Regression  0.121498
4             Decision Tree -0.113295
3    K-Neighbors Classifier -0.641638

In [ ]:
pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_pred,'Difference':y_test-y_pred})
pred_df

     Actual Value  Predicted Value  Difference
281             0                0           0
265             0                0           0
164             1                0           1
9               1                1           0
77              0                0           0
..            ...              ...         ...
94              0                0           0
262             1                0           1
227             0                0           0
272             0                0           0
201             0                0           0

[240 rows x 3 columns]